First pass at setting up one-command training with skypilot. (#298)
Wrote entrypoint for performing training runs with skypilot. The `sky`
command is documented within the `train.sky.yaml` file and contributing
guide.

I did not successfully do a full training run, but that is because I hit
data engineering errors (no static_data!).

<details>
<summary>(Latest error trace related to data engineering)</summary

Ultimately, hitting this error seems like a good sign because the error
is in our code, not in the provisioning system.
```
AssertionError: : Static data variable sea_surface_fraction not found in dataStatic data variable sea_surface_fraction not found in data
```

</details<